# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  unzip,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "10ajn9cva1zcsh0jcfsnc2ckni65nrki4671lgsywwlh8wdpfv1d";
    aarch64-linux = "1s49625fkxd410gf6mgp0rwkwzgzilk363id6nr47gxvfyjys6nz";
    x86_64-darwin = "1xmdhsgh4rvcql1hb9hr0wsndd5dj2szx5yf35amjpdhn9gqka1q";
    aarch64-darwin = "1xmdhsgh4rvcql1hb9hr0wsndd5dj2szx5yf35amjpdhn9gqka1q";
  };

  urlMap = {
    x86_64-linux = "https://downloads.cloudfleet.ai/cli/0.12.0/cloudfleet_linux_amd64.zip";
    aarch64-linux = "https://downloads.cloudfleet.ai/cli/0.12.0/cloudfleet_linux_arm64.zip";
    x86_64-darwin = "https://downloads.cloudfleet.ai/cli/0.12.0/cloudfleet_darwin_all.zip";
    aarch64-darwin = "https://downloads.cloudfleet.ai/cli/0.12.0/cloudfleet_darwin_all.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cloudfleet";
  version = "0.12.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./cloudfleet $out/bin/cloudfleet
    # Docker credential helper symlink
    ln -s $out/bin/cloudfleet $out/bin/docker-credential-cloudfleet
    # Shell completions. The CLI initializes a cache dir under $HOME on
    # every invocation, so give it a writable HOME inside the build sandbox.
    export HOME=$(mktemp -d)
    installShellCompletion --cmd cloudfleet \
    --bash <($out/bin/cloudfleet completion bash) \
    --zsh <($out/bin/cloudfleet completion zsh)
  '';

  meta = {
    description = "Cloudfleet Command Line Interface";
    homepage = "https://cloudfleet.ai";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
