# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  unzip,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1v0gyhy4sr7c4xflwh3darvjn8shavjl3yb0kpif28l89vl1zbv2";
    aarch64-linux = "1pqbc83apgxdxgk4a1v3f02d6lvxb1z4wg25h8xgaci5qfccz1wq";
    x86_64-darwin = "0kk206zys6py6q2chmn75a5ybybrza104jkjjphfw9154cbifg07";
    aarch64-darwin = "0kk206zys6py6q2chmn75a5ybybrza104jkjjphfw9154cbifg07";
  };

  urlMap = {
    x86_64-linux = "https://downloads.cloudfleet.ai/cli/1.2.0/cloudfleet_linux_amd64.zip";
    aarch64-linux = "https://downloads.cloudfleet.ai/cli/1.2.0/cloudfleet_linux_arm64.zip";
    x86_64-darwin = "https://downloads.cloudfleet.ai/cli/1.2.0/cloudfleet_darwin_all.zip";
    aarch64-darwin = "https://downloads.cloudfleet.ai/cli/1.2.0/cloudfleet_darwin_all.zip";
  };
in
stdenvNoCC.mkDerivation {
  pname = "cloudfleet";
  version = "1.2.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles unzip ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./cloudfleet $out/bin/cloudfleet
    # Docker credential helper symlink
    ln -s $out/bin/cloudfleet $out/bin/docker-credential-cloudfleet
    # Shell completions. The CLI initializes a cache dir under $HOME on
    # every invocation, so give it a writable HOME inside the build sandbox.
    export HOME=$(mktemp -d)
    installShellCompletion --cmd cloudfleet \
    --bash <($out/bin/cloudfleet completion bash) \
    --zsh <($out/bin/cloudfleet completion zsh)
  '';

  meta = {
    description = "Cloudfleet Command Line Interface";
    homepage = "https://cloudfleet.ai";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
